# Generated by Django 4.2.7 on 2023-12-03 14:55

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_image1',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_to),
        ),
        migrations.AddField(
            model_name='room',
            name='room_image2',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_to),
        ),
        migrations.AddField(
            model_name='room',
            name='room_image3',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_to),
        ),
        migrations.AddField(
            model_name='room',
            name='room_image4',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_to),
        ),
    ]
